import type { Metadata } from 'next'
import Header from '@/components/Header'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-gray-100'>
      <body className={poppins.className}>
        <Header />
        <div >
        {children}
        </div>
        </body>
    </html>
  )
}
